"""
Relay chain coevolution — A↔B↔C↔D↔A.

Solves the degenerate anchoring problem without external data targets.

The key insight (from the .md Section 4.4 and user clarification):
  A↔A (or A↔B) degenerates because A=B=0 satisfies the joint constraint trivially.
  A↔B↔C↔D↔A does NOT degenerate because the CYCLE only closes coherently if
  each step follows the correct geometric path.

For the 360° rotation case (derivative chain):
  A=cos → B=sin → C=-cos → D=-sin → A=cos
  d/dx applied four times gives d⁴/dx⁴ cos = cos  (cycle closes)
  d/dx applied to zero gives zero  (degenerate solution, zero curvature)

The betweenness constraint distinguishes these:
  Rotational path: Walsh main-effects ALTERNATE even/odd around the cycle
  Degenerate path: Walsh main-effects FLAT (all near zero) around the cycle

The Lorentz/derivative connection:
  The generator of rotation is the derivative operator.
  d/dθ(e^(iθ)) = i·e^(iθ)  — rotation is generated by i (90° phase shift).
  A linear signal molecule encoding derivative structure carries information
  about the CURVATURE of the path, not just its current position.
  By constraining betweenness at each relay step, we constrain the path
  to stay on the rotation manifold rather than taking a trivial straight-line path.

Architecture:
  N populations arranged in a cycle.
  Fitness of population k depends on its two neighbours in the cycle.
  Signal molecules propagate AROUND the cycle (A→B→C→D→A and back).
  The relay population in the middle cannot see A's genotype — only B's signal.
  This forces B to genuinely bridge the algebraic gap between A and C.
"""

import numpy as np
from dataclasses import dataclass, field
from typing import Callable, List, Optional

from toolkit.ga import CoevoConfig
from toolkit.signals import get_signal
from toolkit.walsh import (kl_divergence_spectra, effective_dimensionality,
                            spectral_class)
from toolkit.timing import Timer


@dataclass
class RelayChainConfig:
    n_pops:          int   = 4       # cycle length (4 = 360° rotation)
    step_fitness:    str   = "derivative"  # what each step should do
    # step_fitness options:
    #   "derivative"  — each step is d/dx in phi_k basis
    #   "phase_pi2"   — each step is a π/2 phase rotation
    #   "custom"      — provide step_fns list
    cfg:             CoevoConfig = field(default_factory=CoevoConfig)
    cycle_weight:    float = 0.20    # how much cycle-closure contributes to fitness
    notes:           str   = ""


def _derivative_step(ind_from: np.ndarray, order: float = 1.0) -> np.ndarray:
    """
    Apply fractional derivative of order `order` in phi_k basis.

    order=1.0: full derivative (shift left by 1 index)
    order=0.5: half-derivative (interpolation between identity and full derivative)
    order=1/n: the step size for an n-population relay chain doing one full rotation

    For the quantum well analogy:
      n-population chain should use order=1/n per step, so n steps = 1 full rotation.
      More populations = finer fractional steps = tighter betweenness constraint
      = fewer intermediate states can satisfy all steps simultaneously.

    Implementation: linear interpolation between identity and full derivative.
    True fractional derivative would use Gamma functions; this is the leading-order approx.
    """
    if abs(order - 1.0) < 1e-6:
        return np.append(ind_from[1:], 0.)
    if abs(order) < 1e-6:
        return ind_from.copy()
    # Fractional: blend identity and full shift by `order`
    full_shift = np.append(ind_from[1:], 0.)
    return (1.0 - order) * ind_from + order * full_shift


def _make_step_fitness(step_order: float):
    """
    Return a fitness function for one relay step using fractional derivative of `step_order`.
    step_order = 1/n_pops for an n-population rotation chain.
    """
    def _step_fitness(ind, neighbour_prev, neighbour_next, cycle_weight):
        cost_from_prev = np.linalg.norm(ind - _derivative_step(neighbour_prev, step_order))
        cost_to_next   = np.linalg.norm(neighbour_next - _derivative_step(ind, step_order))
        return -(cost_from_prev + cycle_weight * cost_to_next)
    return _step_fitness


def _step_fitness_derivative(ind: np.ndarray,
                              neighbour_prev: np.ndarray,
                              neighbour_next: np.ndarray,
                              cycle_weight: float) -> float:
    """Full-derivative relay step (order=1.0). Used when n_pops=4."""
    cost_from_prev = np.linalg.norm(ind - _derivative_step(neighbour_prev, 1.0))
    cost_to_next   = np.linalg.norm(neighbour_next - _derivative_step(ind, 1.0))
    return -(cost_from_prev + cycle_weight * cost_to_next)


def _step_fitness_phase(ind: np.ndarray,
                         neighbour_prev: np.ndarray,
                         neighbour_next: np.ndarray,
                         cycle_weight: float,
                         angle: float = np.pi / 2) -> float:
    """
    Fitness for a phase-rotation step.
    ind should equal cos(angle)*prev - sin(angle)*(phase_shifted_prev).
    For angle=π/2: this reduces to the derivative step.
    """
    return _step_fitness_derivative(ind, neighbour_prev, neighbour_next, cycle_weight)


@dataclass
class RelayResult:
    populations:      List[np.ndarray]    # best individual from each population
    cycle_residual:   float               # how well does A→B→C→D→A close?
    step_residuals:   List[float]         # residual at each step
    walsh_signatures: List[np.ndarray]    # Walsh main-effects per population
    spectral_classes: List[str]
    alternating_score: float              # how even/odd do ME alternate? (0=flat, 1=perfect)
    outcome:          str
    timeseries:       dict = field(default_factory=dict)
    timing:           dict = field(default_factory=dict)


def _alternating_score(signatures: List[np.ndarray]) -> float:
    """
    Measure how well the Walsh main-effects alternate even/odd around the cycle.
    Score 1.0 = perfect alternation (cos→sin→−cos→−sin pattern)
    Score 0.0 = flat or non-alternating (degenerate solution)
    """
    if not signatures:
        return 0.0
    scores = []
    for me in signatures:
        even_energy = np.sum(me[0::2] ** 2)
        odd_energy  = np.sum(me[1::2] ** 2)
        total = even_energy + odd_energy + 1e-10
        # Score how unequal even/odd split is (high = dominated by one parity)
        scores.append(abs(even_energy - odd_energy) / total)
    return float(np.mean(scores))


def run(chain_cfg: RelayChainConfig,
        init_pops: Optional[List[np.ndarray]] = None,
        log_every: int = 50) -> RelayResult:
    """
    Run relay chain coevolution.

    Each population is evolved with fitness defined by its two neighbours.
    Signals propagate around the cycle in both directions.
    """
    cfg    = chain_cfg.cfg
    n      = chain_cfg.n_pops
    rng    = np.random.default_rng(cfg.seed)
    signal = get_signal(cfg.signal_design)
    timer  = Timer()

    # Initialise populations
    if init_pops is not None:
        pops = [p.copy() for p in init_pops]
    else:
        pops = [rng.standard_normal((cfg.pop_size, cfg.n_genes)) * 0.3
                for _ in range(n)]

    # Initialise signals for each population (signal FROM k, received by neighbours)
    sigs = [np.zeros(2 ** cfg.n_genes) for _ in range(n)]

    ts = {k: [] for k in ["residuals", "cycle_residual", "alt_score"]}

    # Pick step fitness function.
    # Fractional order: 1/n_pops so that n_pops steps = 1 full rotation.
    # This implements the quantum well analogy: more pops = finer steps = tighter constraint.
    step_order = 1.0 / n
    if chain_cfg.step_fitness == "derivative":
        step_fn = _make_step_fitness(step_order)
    else:
        step_fn = _make_step_fitness(step_order)

    best_pops = [p[0].copy() for p in pops]

    for g in range(cfg.gens):
        # Update signals every sig_freq generations
        if g % cfg.sig_freq == 0:
            with timer.measure("signal_compute"):
                for k in range(n):
                    bk = best_pops[k]
                    fa = lambda ind: step_fn(ind, best_pops[(k-1) % n],
                                             best_pops[(k+1) % n],
                                             chain_cfg.cycle_weight)
                    sigs[k] = signal.emit(pops[k], fa, cfg.n_genes, rng,
                                          cfg.k_signal_samples, cfg.delta)

        # Evolve each population with fitness from its two neighbours
        # Signal received by k: average of signals from (k-1) and (k+1)
        for k in range(n):
            sig_received = 0.5 * (sigs[(k-1) % n] + sigs[(k+1) % n])
            me_received  = signal.receive(sig_received, cfg.n_genes)
            mut_std      = cfg.mut_std * (1.0 + cfg.sig_weight * me_received)

            fits = np.array([
                step_fn(ind, best_pops[(k-1) % n], best_pops[(k+1) % n],
                        chain_cfg.cycle_weight)
                for ind in pops[k]
            ])

            elite_idx  = np.argsort(fits)[-cfg.elite:]
            new_pop    = np.empty_like(pops[k])
            new_pop[:cfg.elite] = pops[k][elite_idx].copy()

            for j in range(cfg.elite, cfg.pop_size):
                idx  = rng.choice(cfg.pop_size, cfg.tourney, replace=False)
                p1   = pops[k][idx[np.argmax(fits[idx])]]
                idx  = rng.choice(cfg.pop_size, cfg.tourney, replace=False)
                p2   = pops[k][idx[np.argmax(fits[idx])]]
                mask = rng.random(cfg.n_genes) < 0.5
                child = np.where(mask, p1, p2)
                child += rng.standard_normal(cfg.n_genes) * mut_std
                new_pop[j] = child

            with timer.measure("ga_step"):
                pops[k] = new_pop

            # Update best
            fits2       = np.array([step_fn(ind, best_pops[(k-1)%n],
                                             best_pops[(k+1)%n],
                                             chain_cfg.cycle_weight)
                                     for ind in pops[k]])
            best_pops[k] = pops[k][np.argmax(fits2)].copy()

        # Log
        if g % log_every == 0:
            step_res = [
                float(np.linalg.norm(best_pops[k] - _derivative_step(best_pops[(k-1)%n])))
                for k in range(n)
            ]
            # Cycle residual: how well does D→A close?
            cycle_res = float(np.linalg.norm(
                best_pops[0] - _derivative_step(best_pops[-1])
            ))
            mes = [signal.receive(sigs[k], cfg.n_genes) for k in range(n)]
            alt = _alternating_score(mes)
            ts["residuals"].append((g, step_res))
            ts["cycle_residual"].append((g, cycle_res))
            ts["alt_score"].append((g, alt))

    # Final diagnostics
    step_residuals = [
        float(np.linalg.norm(best_pops[k] - _derivative_step(best_pops[(k-1)%n])))
        for k in range(n)
    ]
    cycle_residual = float(sum(step_residuals))
    mes  = [signal.receive(sigs[k], cfg.n_genes) for k in range(n)]
    scs  = [spectral_class(me) for me in mes]
    alt  = _alternating_score(mes)

    if cycle_residual < 0.40:
        outcome = "correct"
    elif alt < 0.1:
        outcome = "degenerate"
    else:
        outcome = "partial"

    return RelayResult(
        populations=best_pops,
        cycle_residual=cycle_residual,
        step_residuals=step_residuals,
        walsh_signatures=mes,
        spectral_classes=scs,
        alternating_score=alt,
        outcome=outcome,
        timeseries=ts,
        timing=timer.to_dict(),
    )
